Require Rust 1.62 for enum defaults
All our examples use codegen from `graphql_client_codegen` which
uses [enum defaults][1] which are only [supported as of 1.62][2].

This commit makes that requirement explicit for a more helpful error
message:

> $ cargo build
> error: package [..] ([.. path..]])` cannot be built because it
> requires rustc 1.62.0 or newer, while the currently active rustc
> version is 1.61.0

[1]: https://github.com/graphql-rust/graphql-client/blob/33b8a34aabbaaac9977a93763ae445dc64b5c67c/graphql_client_codegen/src/deprecation.rs#L10-L20
[2]: https://github.com/rust-lang/rust/pull/94457#event-6442293650